# .circleci/config.yml
version: 2.1
orbs:
  node: circleci/node@5

jobs:
  
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building things..."

  # jobs pour les tests unitaires
  unit_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running unit tests"

  # jobs pour les tests d'intégration
  integration_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running integration tests"

  # jobs pour les tests de régression
  regression_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running regression tests"

  # jobs pour les tests d'accessibilité
  accessibility_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running accessibility tests"

  # jobs pour les tests de compatibilité
  compatibility_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running compatibility tests"

  # jobs pour les tests de performance
  performance_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running performance tests"

  # jobs pour les tests de sécurité
  security_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running security tests"

  # jobs pour deploiement developpement
  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  # jobs pour deploiement production
  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

  # jobs pour deploiement d'integration
  deploy_integration:
    executor: node/default
    steps:
      - checkout
      - run: echo "integrate to integration environment..."

  # jobs pour deploiement de fonctionnalité
  deploy_feature:
    executor: node/default
    steps:
      - checkout
      - run: echo "featuring to feature environment..."

  # jobs pour deploiement correctifs
  deploy_hotfix:
    executor: node/default
    steps:
      - checkout
      - run: echo "hotfix to hotfix environment..."

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
          filters:
            branches:
             ignore:
                - /^feature\/.*/
                - /^hotfix\/.*/

      - integration_tests:
          requires:
            - build
          filters:
            branches:
             ignore:
                - /^feature\/.*/
                - /^hotfix\/.*/

      - performance_tests:
          requires:
            - build

      - regression_tests:
          requires:
            - build

      - accessibility_tests:
          requires:
            - build
          filters:
            branches:
             ignore:
                - /^feature\/.*/
                - /^hotfix\/.*/

      - compatibility_tests:
          requires:
            - build

      - security_tests:
          requires:
            - build
          filters:
            branches:
             ignore:
                - /^feature\/.*/
                - /^hotfix\/.*/

      - deploy_dev:
          requires:
            - security_tests
            - unit_tests
            - integration_tests
            - regression_tests
            - accessibility_tests
            - compatibility_tests
            - performance_tests
          filters:
            branches:
              only:
                - develop

      - deploy_integration:
          requires:
            - security_tests
            - unit_tests
            - integration_tests
            - regression_tests
            - accessibility_tests
            - compatibility_tests
            - performance_tests
          filters:
            branches:
              only:
                - integration

      - deploy_prod:
          requires:
            - security_tests
            - unit_tests
            - integration_tests
            - regression_tests
            - accessibility_tests
            - compatibility_tests
            - performance_tests
          filters:
            branches:
              only:
                - main

      - deploy_feature:
          requires:
            - regression_tests
            - performance_tests
          filters:
             branches:
              only:
                - feature

      - deploy_hotfix:
          requires:
            - compatibility_tests
            - performance_tests
          filters:
             branches:
              only:
                - hotfix